### PR TITLE
ENHANCED: handle C++ functions, add cxxfuncref

### PR DESCRIPTION
**Pull request by kamahen**

### CODE REVIEW

**Comment by kamahen** [comment]
The change to CMake is a commented-out `pkg_doc` that didn't work ... perhaps this package isn't intended to show on the SWI-Prolog web pages?

The `catch_with_backtrace/3` change was intended to help find obscure markup errors (see https://github.com/SWI-Prolog/packages-swipy/pull/5), but it didn't output a traceback; I had to run the command in a shell and use the debugger to generate a traceback (which found the markup error).

**Comment by JanWielemaker** [comment]
Thanks.   Only copied the \cxxfuncref stuff.   The rest either does not work or just obfuscates (`% '`).  I guess this is to make Emacs happy?   Try Eshel's sweep mode.    Quite impressive and it has a correctly working Prolog indentation and syntax highlighting.

I guess it is possible to get the documentation in.   I don't want to advertise this as a public library though.  It is there just to manage the documentation as far as I'm concerned.

**Comment by kamahen** [comment]
Sorry about leaving in the `% '` comments (which were for fixing emacs token colouring) - I had meant to remove them and forgot. I'll try package "sweep" - when it first came out, it didn't work for me, and I hadn't revisited it.

The documentation for `catch_with_backtrace/3` says "This is good practice for a _catch-all_ wrapper around an application", so I'm curious why you removed it? Although it didn't have the desired  effect for me - I had to run the command by hand to get a backtrace from the debugger.

Question: I'd like to generate the documentation locally (so that I don't bother you with so many questions) - and tried adding this to `CMakeLists.txt`, which didn't  work: `pkg_doc(ltx2htm SOURCE latex2html.pl ltx2htm.doc)` ... how should I generate the documentation?
(Also, what's the difference between `SOURCE` and `SOURCES`?)

**Comment by JanWielemaker** [comment]
> so I'm curious why you removed it?

I understood it didn't work.    That, in my view, means we must fix it before adding it to the system or leave it out.    If it did work, please re-add.

> how should I generate the documentation?

I don't know.   Something along the lines you tried.    But, the docs are really old and have never been updated.  So, probably they do not build and if we fix them just to make them build the content is probably 80% outdated.    I don't know how useful it is to fix that.    Ideally, I guess, the entire documentation pipeline should be modernized.    That is a huge project.     It would be nice as it makes it easier for people to improve the docs, but otherwise the result of all that work will be small.

**Comment by kamahen** [comment]
Following up on the catch-with-backtrace ... if I run latex2html.pl from the command line, without the `--quiet` option, I get thrown into the debugger, and the `g` command gives me enough information to figure out what source text was being processed. (The backtrace doesn't display deep enough)

**Pull request closed without merging**
